name: Deploy Laravel school Erp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  
            
      - name: sync files to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/var/www/sms.infiniasync.com/html"
          strip_components: 0

      - name: Run Laravel deployment commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/sms.infiniasync.com
            echo "Setting up Laravel..."
            # Install dependencies (if you want to run composer on server)
            # composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            # Setup permissions
            chown -R www-data:www-data .
            chmod -R 755 storage
            chmod -R 755 bootstrap/cache
            
            # Clear and cache
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            
            # Optional: only run if you want to cache config in production
            # php artisan config:cache
            # php artisan route:cache
            # php artisan view:cache
            
            echo "Deployment complete!"